# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  publisher: 'capgemini-msft-uk'

stages:
  - stage: Build
    jobs:
    - job: BuildJob
      displayName: Build
      steps:
      - task: NuGetToolInstaller@0
        displayName: 'Use NuGet 5.2.0'
        inputs:
          versionSpec: 5.2.0

      - task: NuGetCommand@2
        displayName: 'NuGet restore'
        inputs:
          restoreSolution: '$(solution)'
          feedsToUse: config
          nugetConfigPath: NuGet.config

      - task: VSBuild@1
        displayName: 'Build solution **\*.sln'
        inputs:
          solution: '$(solution)'
          platform: '$(BuildPlatform)'
          configuration: '$(BuildConfiguration)'

      - task: VSTest@2
        displayName: 'VsTest - testAssemblies'
        inputs:
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
          codeCoverageEnabled: true
          testAssemblyVer2: |
             **\*Tests*.dll
             !**\*Integration*.dll
             !**\obj\**

      - task: CopyFiles@2
        displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
        inputs:
          SourceFolder: '$(system.defaultworkingdirectory)'
          Contents: '**\bin\$(BuildConfiguration)\**'
          TargetFolder: '$(build.artifactstagingdirectory)'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: drop'
        inputs:
          PathtoPublish: '$(build.artifactstagingdirectory)'

  - stage: PublishtoPrivateMarketPlace
    displayName: Publish to Private MarketPlace
    jobs:
      - job: PublishPrivateJob
        displayName: Publish to Private MarketPlace        
        steps:
        - checkout: none
        - download: current
        - task: ms-devlabs.vsts-developer-tools-build-tasks.publish-extension-build-task.PublishExtension@1
          displayName: Publish to Private MarketPlace        
          inputs:
            connectedServiceName: 'Capgemini MarketPlace Publishers'
            fileType: vsix
            vsixFile: '$(Pipeline.Workspace)/drop/Azure.DevOps.Extensions.XrmRelease/Azure.DevOps.Extensions.XrmRelease/bin/Release/capgemini-uk.xrm-release-*.vsix'
            publisherId: '$(publisher)-dev'
            extensionId: 'capgemini-xrm-release-extension'
            extensionName: 'Capgemini Release Extension for Dynamics 365'
            updateTasksVersion: false
            extensionVisibility: private
            extensionPricing: free

  - stage: PublishToPublicMarketPlace
    displayName: Publish to Public Feed
    condition: succeeded()
    jobs:
      - deployment:
        environment: Public Visual Studio MarketPlace
        strategy:
          runOnce:
            deploy:
              steps:
              - task: ms-devlabs.vsts-developer-tools-build-tasks.publish-extension-build-task.PublishExtension@1
              displayName: 'Publish to Public MarketPlace'        
              inputs:
              connectedServiceName: 'Capgemini MarketPlace Publishers'
              fileType: vsix
              vsixFile: '$(Pipeline.Workspace)/drop/Azure.DevOps.Extensions.XrmRelease/Azure.DevOps.Extensions.XrmRelease/bin/Release/capgemini-uk.xrm-release-*.vsix'
              publisherId: '$(publisher)'
              extensionId: 'capgemini-xrm-release-extension'
              extensionName: 'Capgemini Release Extension for Dynamics 365'
              updateTasksVersion: false
              extensionVisibility: public
              extensionPricing: free